<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <None Include="..\LICENSE" Link="LICENSE">
      <PackagePath>\</PackagePath>
      <Pack>True</Pack>
    </None>
    <None Include="..\README.md" Link="README.md">
      <PackagePath>\</PackagePath>
      <Pack>True</Pack>
    </None>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="KubernetesClient" Version="19.0.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\DMCorp.Framework.Basics\DMCorp.Framework.Basics.csproj" />
  </ItemGroup>

</Project>
