name: Build - Pack - Push to NuGet

on:
  push:
    branches: [ "master" ]
    #tags: ['v*.*.*']
  pull_request:
    branches: [ "master" ]
    types: ["closed"]
    tags: ['v*.*.*']

jobs:
  build-and-publish:
    permissions:
      contents: read
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --c Release --no-restore

      - name: Pack NuGet package
        run: dotnet pack --c Release --no-build --output OutNuGet

      #- name: dotnet pack
      #  run: dotnet pack
        # dotnet pack -r win-x64
